name: Publish npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Updated to the latest version

      - name: Setup Node.js
        uses: actions/setup-node@v3 # Updated to the latest version
        with:
          node-version: '20'
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm i --legacy-peer-deps

      - name: Run tests
        run: npm test # Ensure tests pass before publishing

      - name: Build project
        run: npm run build # Ensure the project is built before publishing, if needed

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.COMP_LIB}}
